### ISSUE TITLE
自定义favicon

### ISSUE THREAD

**Issue by floperry** [ColMugX/hexo-theme-Nlvi#10]
您好，很喜欢这款Nlvi主题，目前正在使用中。但是配置过程中遇到一个小问题，我想要自定义favicon，不太清楚具体应该修改哪部分，请教一下有没有什么好的建议？

**Comment by colmugx** [comment]
如果wiki没有那就是我的锅！

主题的`_config.yml`中
```yaml
# favicon
favicon:
```
后面填上favicon的地址即可。

**Comment by floperry** [comment]
试了一下，好像并没有成功...比如说我现在有一个favicon.ico文件和_config.yml在同一目录下，那么我应该在favicon:后填入什么呢？

**Comment by colmugx** [comment]
你想办法让favicon有一个http地址，这是无法避免的。你可以上传github之后，然后去找出favicon.ico的地址出来然后再贴进去再更新一次。

给个建议，你放进博客的source文件夹（不是主题的！）
