### ISSUE TITLE
設置字體

### ISSUE THREAD

**Issue by shadowquark** [ColMugX/hexo-theme-Nlvi#12]
您好。對您製作的主題很感興趣。感謝您的辛勤勞動。

在主題的設置中。字體似乎只有默認。雅黑等不多的選擇。麻煩問下有可能使用自己選擇的字體嗎。

非常感謝。
祝好。

**Comment by colmugx** [comment]
关于定制的话，我是特别想满足任何一个人的。

如果有这类需求的话，我会尽量满足。

- [x] 在`_config.yml`配置字体

**Comment by colmugx** [comment]
患病一周没有使用电脑，如对你带来不便，抱歉

**Comment by shadowquark** [comment]
我發完帖子後也生病了。剛剛康復。

目前在 _config.yml 中只能配置您給定的幾種字體吧。似乎暫時無法支持本地的 ttf otf 等字體文件。個人覺得似乎能分別設置一個 CJK 字體。一個西文字體和一個等寬字體。會是比較便捷的。否則如果能支持公認比較優秀的思源黑體和思源明體。那麼在不同平臺上都會有比較理想的效果。

感謝您的回覆。我給一些人看了您製作的主題。設計方面收到的大多數是好評。不過功能方面似乎比起較爲流行的 NexT 還有一定差距。

最後。因爲我對前端和 UI 設計都是外行。所以有一個可能是亂說的看法。僅供參考。搜索功能的 alpha 值似乎可以調整一下。現在透明度有點太高。這樣搜索結果和背景有點重合在一起。就看不太清搜索結果了。效果如下。

![image](https://user-images.githubusercontent.com/9638795/28719654-056fdbac-73ab-11e7-9186-a1b324977e92.png)

**Comment by colmugx** [comment]
谢谢

暂时就是想按照您说的，可以配置自定义字体名字达到效果。至于分别设置字体，这个我倒是要看看怎么做比较好。

至于跟NEXT比较，那就真的抬举我了，人家那个项目已经做成社区了（逃

好评倒是没有那么夸张，毕竟我们做着玩，然后有人“哇！喜欢！”。这个时候我才知道，我得为nlvi的粉丝负责了！

至于UI，我也没受过什么专业学习，是个建议都会接受。不过针对透明度，我倒是制作的时候来来回回对比了很多版，就目前的效果来说是比较漂亮的。如果还是有阅读问题的话，调整！

**Comment by colmugx** [comment]
老哥，关于自定义字体的事，我找了一个比较不妥的方式。暂时先这样。以后想到好的方法我会告诉你的。

现在在主题的`source`中，`style`目录下，有一个`_custom.styl`，这个文件优先级算是比较高的，你可以把你喜欢的字体按西文到中文的顺序填到`custom-fonts-style`后，怎么填我已经在文件给了例子。

然后`_config.yml`还是设置字体那里，改成`Custom`即可

本地字体的话，你可以直接就在`_custom.styl`写你的配置，如果不清楚的话，具体我会更新wiki。

本来想在`_config.yml`一条龙解决，看来还是不行呢（笑

**Comment by shadowquark** [comment]
您好。感謝您的辛勤勞動。

您默認的樣例 ``_custom.styl`` 中包括了三個字體。第一個苹方。第二個是冬青黑。第三個是 Roboto。看起來是中文到西文的順序。而不是西文到中文。麻煩問下這三個字體分別對應了怎樣的設置呢。如果按照您這個文件這樣設置。最後的 CJK 字體到底是蘋方還是冬青黑呢。

**Comment by shadowquark** [comment]
$fonts-style = hexo-config("fonts-style")
$font-article-YaHei = 'Microsoft YaHei', "微软雅黑", sans-serif
$font-article-Hel = 'Helvetica', 'Hiragino Sans GB', 'Roboto', 'Noto SansCJK', 'Heiti TC', 'Heiti SC', sans-serif
$font-article-Simsun = 'Times New Roman', 'Simsun', 'STSong', '华文宋体', sans-serif

在您的這個配置文件中。不同的字體配置是一個長度不等的序列。所以我有點困惑這些字體分別對應了什麼設置。

**Comment by colmugx** [comment]
`_custom.styl`是我随便写的，立刻能想到的三个就直接写上了，给你带来困扰真是不好意思…

如果你自己填写，按照其他字符 -> 西文 -> CJK -> `serif`来填写。

最后这个`serif`有两个答案，一个是`sans-serif`，另一个是`serif`，填这个的原因是：在浏览器都找不到你前面填写的那些字体的时候，采用浏览器默认字体来显示，`sans-serif`是默认无衬线字体，`serif`是衬线字体，请务必记得添加。

至于下面那个疑问…我解释起来就费劲了…如果您确实喜欢思源体的话，我下个更新会给你提供一个版本，你看这样行不行

**Comment by colmugx** [comment]
为什么说西文放前面，是因为浏览器找字体的流程就是：该字符在该字体找不到时，跳到下一字体查找。

所以一般西文字体，是不会有中文字体的。故放前面。如果你把类似于苹方字体放前面，那么苹方字体的范围是西文CJK都有，那么就会直接把全部字体交给苹方处理。但是非apple设备是不会有苹方字体的，故所有字体的适配跳到下一字体也就是可能但不限于`Helvetica`字体，当然这也是我设定的

**Comment by shadowquark** [comment]
啊。多謝解釋。我自己搞定了。我可能是 latex 用多了。總覺的應該有特別詳細的一套 setXXXfont。尤其是對於等寬體有一些執着的選擇傾向。現在這樣我只要默認用思源黑或者思源明就行了。雖然達不到完全理想的強迫症效果。但設置起來倒是簡單了。
