### ISSUE TITLE
網易雲跟帖和多說似乎已經關閉了

### ISSUE THREAD

**Issue by shadowquark** [ColMugX/hexo-theme-Nlvi#13]
網易雲跟帖 8 月 1 日關閉了。
https://www.zhihu.com/question/45818269
多說也關閉了。
https://www.zhihu.com/question/57426274

似乎可以去掉這兩部分支持了。不知道還有啥好的評論系統可用。

**Comment by colmugx** [comment]
- [x] Gitment
- [x] 畅言
