### ISSUE TITLE
是否有插件的功能

### ISSUE THREAD

**Issue by ruinshe** [ColMugX/hexo-theme-Nlvi#17]
用了你的hexo theme有一段时间了（感觉很好，特别是对我这种对UI完全没感觉的人，还有动画效果很赞

不知道有没有办法支持插件的功能，我现在为自己的网站加了一些额外的支持（比如说`MathJax`和特定的photo layer），但是感觉直接merge到这边会比较多余。

如果能支持的话，倒是可以把这些额外的又比较常用的功能整合一下。

目前想到一个办法是直接在`_config.yml`里面加个类似`support_mathjax`的，但是感觉整个主题的代码充斥着各种if else特别不爽。。。

**Comment by colmugx** [comment]
没有自定义插件的功能，也不知道怎么实现比较漂亮。

关于主题的话，其实我打算空出时间来重构，我发现之前有点初生牛犊，CSS跟JS都写得不好。

如果有更好的实现方式的话，我很希望你能帮我喔~

**Comment by colmugx** [comment]
@ruinshe 
老哥，主题大改了一遍，关于JS的结构也改了一下。`plugin`原型链的方法会直接运行。

我也没用过`mathjax`，我希望老哥能提供支援！

**Comment by ruinshe** [comment]
mathJax的patch在[这里](https://gist.github.com/ruinshe/8dc3373d3df8c79a12beaea3b8ef4b31)，暂时没有时间看你第二版的plugin的目录结构了所以直接把patch给你了，你可以考虑加一下（不过MathJax这东西真的会有人用么。。）

改动特别小嗯

**Comment by colmugx** [comment]
ok！
