### ISSUE TITLE
当页面内容较多时，文章导航栏后半部分内容无样式，变成了普通的蓝色带下划线的链接样式。

### ISSUE THREAD

**Issue by super2bai** [ColMugX/hexo-theme-Nlvi#18]
<img width="217" alt="qq20171026-151356 2x" src="https://user-images.githubusercontent.com/5546192/32039351-5ac4ceda-b9f3-11e7-9b87-2b896c4dd62d.png">

如上图所示，curator及下面导航内容，无样式。

**Comment by colmugx** [comment]
奇怪，不太可能的。这部分我当时测试很多次。我空下来的时候看一下吧

**Comment by super2bai** [comment]
https://super2bai.github.io/2017/10/25/Zookeeper%E5%AE%A2%E6%88%B7%E7%AB%AF/
这个链接是我创建的页面，标题为“Zookeeper客户端”的那一篇文章，您可以debug一下。

**Comment by ruinshe** [comment]
灰色的样式是
```css
.post-toc .toc .toc-item {
    color: #666;
}
```
后面蓝色link的样式没有`.toc`这个class（好奇怪


PS: 我看到github.io的repository，这个是你hexo生成的还是说手写的html（大概不会是手写的吧。。。

**Comment by colmugx** [comment]
@ruinshe 我昨天看的时候，那部分没有样式的是越界了，它并没有在`<ol></ol>`标签内。

那肯定得是生成的啦！实际上我昨天还在奇怪来着，就是太没时间

**Comment by colmugx** [comment]
@super2bai @ruinshe 

https://colmugx.github.io/PersonalBlog/2017/10/27/toc-test/

我晚上删掉这篇文章

**Comment by dmego** [comment]
😊发现一个小问题，博客左上角logo的链接似乎没有改过来，点击跳转到的是https://colmugx.github.io/
而非https://colmugx.github.io/PersonalBlog/

**Comment by colmugx** [comment]
@dmego 新版本不会出现这个问题了，谢谢提供问题
