### ISSUE TITLE
请问如果不想标题前面出现那个音乐符号，改动css就可以了吗

### ISSUE THREAD

**Issue by Tvinsh** [ColMugX/hexo-theme-Nlvi#2]
请问如果不想标题前面出现那个音乐符号，改动css就可以了吗

**Comment by ruinshe** [comment]
FYI, file `source/style/_partial/post.styl` line 64

**Comment by colmugx** [comment]
在`source/style/_partial/post.styl`的第65行，如果你不喜欢可以改成你喜欢的或者直接只留下空格。我在下个版本改成可以自定义吧

**Comment by colmugx** [comment]
已经更新
