### ISSUE TITLE
文字整体看上去太紧凑了 比如首页所有文章

### ISSUE THREAD

**Issue by 369pie** [ColMugX/hexo-theme-Nlvi#20]
怎么能适当调节下 求教~~

**Comment by colmugx** [comment]
可以给个截图，然后说一下你预想的舒展是什么样子的。

如果好的改进，我愿意去做！！

**Comment by 369pie** [comment]
![image](https://user-images.githubusercontent.com/22891991/32543939-09f027a6-c4b2-11e7-800c-83bd28ebb3a7.png)
比如这里加2个换行...  就是文章和文章之间隔开一点

**Comment by 369pie** [comment]
其次 能不能在wiki增加一个 怎么自己能修改样式的简短教程 举一个例子就行... ^_^

**Comment by 369pie** [comment]
正文的默认灰色好像太淡了你不觉得吗  有点看不太清的感觉 字体大小默认可以再大一点点

**Comment by colmugx** [comment]
第一个建议：我会考虑一下然后下一次更新的时候加上去

第二个建议：当然可以！不过我想让这些操作更容易操作一些，所以目前先不出。但是也是不久后。

第三个建议：这是我的问题！因为长期在mac上，所以是完全疏忽了Windows体验。在考虑EDGE和关于Windows没有苹方字体这方面我想改进想了很久了，给您造成不便请原谅不要捶我（自觉顶锅）

**Comment by 369pie** [comment]
expecting : ) 我先自己尝试修改下
