### ISSUE TITLE
标签云的显示不好看

### ISSUE THREAD

**Issue by DoneSpeak** [ColMugX/hexo-theme-Nlvi#21]
标签云真心不好看

**Comment by colmugx** [comment]
指点一二？

**Comment by LIUYOU2015** [comment]
我也这么觉得，原因有二：
1. 点击标签之后出来一个“悬浮窗”，上面标签的字体过小。
2. 鼠标停留在标签上时有阴影，体验不是很好。

**Comment by colmugx** [comment]
@LIUYOU2015 谢谢！

不过…你认真的嘛…新主题没有阴影，而是下划线，并且现在颜色可以根据自己心情改动的

**Comment by colmugx** [comment]
@LIUYOU2015 你的意见我会考虑的，还有你竟然换了Even哈哈
