### ISSUE TITLE
代碼的等寛字體和導航的自動隱藏

### ISSUE THREAD

**Issue by shadowquark** [ColMugX/hexo-theme-Nlvi#22]
似乎在自己設置了字體後。代碼就不再默認使用等寛字體。而是直接使用優先級最高的字體。

此外。當窗口縮小。或內容放大時。右側的導航列會和文章重疊起來。

這兩個 bug 目前感覺都有些致命。參見下圖。

![2017-11-28 13-50-39](https://user-images.githubusercontent.com/9638795/33320721-6bfe8e4c-d443-11e7-826f-8ee73e0ea6fb.png)

不知道容易解決麼。

**Comment by colmugx** [comment]
主题大改已经提上队列了，只是时间问题，有点排不上档期…

所以您的两个问题，我就直接针对性的改一下。

有打算给“文章目录”加上开关，但这是下个版本的事了，您觉得怎样？

- [x] 代码字体被污染

- [x] 文章目录错位

**Comment by shadowquark** [comment]
文章目錄加上開關是很完美的解決方案。

代碼不用等寛字體的問題。我看了下您自己的的主頁。

https://colmugx.github.io/PersonalBlog/2017/08/14/js-call-apply-bind/

發現也是存在的。我自己瞎搗鼓了一陣子。沒有成功。。。不知道要在哪裏改。。。只能希望您多費心了。。。

**Comment by colmugx** [comment]
代码等宽已经一并修复了的，我知道自己的代码字体有问题…

暂时先这样吧。

**Comment by shadowquark** [comment]
啊。抱歉。我沒搞明白。現在 ``` ``` 之間的代碼還是沒有用等寛字體啊。如何讓代碼用等寛字體呢。

**Comment by shadowquark** [comment]
https://github.com/ColMugX/hexo-theme-Nlvi/blob/master/source/style/_partial/_code/highlight.styl

感覺問題出在這裏。你這裏列的字體都不是等寛字體。所以顯示出來也不是。我強行在這裏面 import 了 Roboto Mono 就能顯示等寛代碼了。但是整個頁面的 parse 就壞掉了。不知道哪裏出了問題。

我感覺你應該透露一下在哪導入字體是正確的。然後大家可以
import url( "https://fonts.google.com/specimen/Roboto+Mono" )
再調用自己喜歡的字體就行了。

我試着在 style.styl 裏面 import 了 web fonts。但是完全不起作用。。。不知道咋辦了。。。而且我在 _partial/_code/highlight.styl 裏面把字體改成了我電腦裏面有的 mono font 似乎也不起作用。太詭異了。。。

**Comment by colmugx** [comment]
更新了，你现在可以按照自己的喜好自定义。
方式参照：https://github.com/ColMugX/hexo-theme-Nlvi/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%96%87%E7%AB%A0%E5%AD%97%E4%BD%93

如果你在`_config.yml`中把`code-style`改成`Custom`的话

字体会引用文档所述的文件中，`$custom-code-fonts-style` 后面的字体配置进行设置

当然还是跟设置文章字体一样，你可以自己贴入`@font-face`

**Comment by shadowquark** [comment]
成功改了 monospace。多謝您的更新。您這個主題已經比很多 fork 幾百次的主題，功能和設置還全了。

對於 font 的問題。我覺得最終極的解決方案可能就是能 import url( "" ) 使用 web 字體。如果能在您的 Custom 設置中使用 web 字體。將能一勞永逸地解決字體問題。 當然我不太懂相關的技術。不知道這麼做的複雜度高不高。

再次感謝您的辛勤勞動。期待您未來的進一步更新。

**Comment by colmugx** [comment]
@ShadowQuark 

新的版本已经放出，除了更新了主题，还有您之前提的两个issue所更新的两个功能

还添加了toc收回功能

感谢您一直支持（好像就您的问题提的最多了…甚至还把小nlvi拿去跟next对比…）
