### ISSUE TITLE
点击文章右侧的标题目录,无法跳转

### ISSUE THREAD

**Issue by zachaxy** [ColMugX/hexo-theme-Nlvi#25]
如题,文章右侧显示的标题目录,不能点击,但是看到您的博客点击是可以跳转的?
(已经在主题中配置了 toc: true)
我的博客地址: https://zachaxy.github.io/ 
可以帮忙看下吗,多谢啦

**Comment by colmugx** [comment]
奇怪，我看不出来。你的markdown有什么问题吗？

**Comment by zachaxy** [comment]
markdown感觉也没什么问题，我记得之前的文章是可以跳转的，今天发现所有的都不能跳了，如果要排查问题的话，需要从哪里入手呢？

**Comment by zachaxy** [comment]
点击标题文字不能跳转，而点击每个标题左侧的空白，就可以跳转，但是跳转并不是对应的。
eg：点标题2左侧，会滑动到标题1对应的位置。。。

**Comment by zachaxy** [comment]
右侧标题无法点击的问题，目前已解决。之前不能点击是我在mac上发布的，现在再另一台win上发布，发现又可以点击了。对比两台机器不同的地方是mac上的pacage.json中的hexo的version为3.4.3，而win上hexo的version是3.4.2。但具体原因就不知道了。
同时发现了一个问题，包括在您的博客中也存在，就是点击标题2，标题1会高亮，可能是个bug

**Comment by ahonn** [comment]
@zachaxy @ColMugX 
Hexo 官方引入的 Bug 导致，安装 3.4.2 版本即可解决。
具体导致 TOC 失效的 Commit 是 [fix(toc): title should escape html entities](https://github.com/hexojs/hexo/commit/284c1b93824348a44884a7354214c050672e74bf)

**Comment by colmugx** [comment]
@ahonn 又被大佬照顾了一下…

@zachaxy 那个是就那个样子的，在看到标题的位置都会亮

**Comment by ahonn** [comment]
具体原因：https://github.com/hexojs/hexo/issues/2896
