### ISSUE TITLE
想问个问题，不清楚这是主题都原因都还是我自己不会弄都原因

### ISSUE THREAD

**Issue by psyvirgin** [ColMugX/hexo-theme-Nlvi#29]
我在使用的过程中发现，比如我点article或者主页或者about可以访问网站，但是连接archives的时候有这样都问题：
1.手机端访问archives可以访问，但是PC端访问不行。用IP解释可以这样  比如我访问都域名指向的IP和端口是 11.11.11.11:8888,按理访问archives应该是11.11.11.11:8888/archives,手机访问的地址是这个，但是PC端访问的地址却是11.11.11.11/archives；
2.蹊跷的是点网页的about，PC和手机浏览器指向的地址都是11.11.11.11:8888/about
也许是nginx设置的不对，可否解答下？
感谢唯盼！

**Comment by psyvirgin** [comment]
补充一下，在localhost:4000下是正常的！

**Comment by colmugx** [comment]
我的主题得有多大能耐才能把8888变成80啊…

你的情况我也不敢随便下定论，你的问题我可能帮不了你。

你在本地测试是正常的应该跟`hexo`或者`nlvi`没有关系。hexo生成之后会得到一个`public`的文件夹，直接用这个文件夹做代理就好了。

**Comment by psyvirgin** [comment]
谢谢，自己弄好了 
用nginx转发搞好了
