### ISSUE TITLE
问题：博客主界面的tags按钮显示的链接是”JavaScript:;“，而其他的按钮都是正确的链接。

### ISSUE THREAD

**Issue by GaoGorden** [ColMugX/hexo-theme-Nlvi#30]
<li class="menu-item">
      <a href="javascript:;" id="tags">
        <span class="base-name">标签</span>
        
          <span class="menu-item-label">tags</span>
        
      </a>
    </li>  

这个是 /public 文件夹中的 index.html 中的代码。

执行命令 hexo new page tags 之后， 
sources/tags 的 index.md文件也修改了type: “tags” ，
主题配置文件的 tags: /tags 也设置了。

但是博客主页面的“ tags 标签”按钮没有网页链接。

**Comment by colmugx** [comment]
`_config.yml`中设置的`tags`的地址是个摆设，实际上被`JavaScript`接管了，文件在这https://github.com/ColMugX/hexo-theme-Nlvi/blob/master/layout/_partial/_header/nav.swig

相关方法：https://github.com/ColMugX/hexo-theme-Nlvi/blob/master/source/script/scheme/balance.js#L48

或者：https://github.com/ColMugX/hexo-theme-Nlvi/blob/master/source/script/src/utils.js#L24

看用的主题而定（感觉要修改一下有点乱）

**Comment by GaoGorden** [comment]
想问下博主的 tags 效果是怎么实现的，小弟不才，JS代码看的一知半解，还是不清楚该如何配置。
我使用的是 balance 主题。

**Comment by colmugx** [comment]
您是要显示标签？您的文章设置了标签了没有？
按正常来说，你的文章文件(markdown)头部应该有这些信息

```markdown
---
title: 
date: 
tags: [your_tag]
categories: your_category
---
```
然后相对的，文章会被归类到某个标签，归类到某个归档。左边的标签也能正常显示了

**Comment by GaoGorden** [comment]
感谢博主的耐心回答，我的博客的标签都设置了，但是博客主界面左边的 ”标签“ 按钮，点击了并没有任何反应，不知如何设置。这是我的主界面：https://gordenyou.github.io/

**Comment by shadowquark** [comment]
我用老版直接能顯示出來的標籤。改了新版之後就出不來了。跟 lz 完全一樣的情況。還沒研究出爲啥。我再研究一陣子。

**Comment by shadowquark** [comment]
另外搜索功能設置成 true 後也有同樣地問題。點了之後出不來。

**Comment by colmugx** [comment]
@ShadowQuark balance的搜索功能我没做…最近事情太多了。

针对tagcloud的问题，我会把banderole和balance都测试一遍

**Comment by colmugx** [comment]
@GORDENyou @ShadowQuark 

因为我的博客结构跟各位直接构建的不太一样，给各位带来麻烦了。请下载最新最新的版本就可以用了。

如果还有同样的问题，请直接在这里回复。

不过如果使用 balance 的话，搜索功能依然无效。工作多身体又差的人活着真不易……
