### ISSUE TITLE
请问怎么修改行间距

### ISSUE THREAD

**Issue by hooshooo** [ColMugX/hexo-theme-Nlvi#32]
主题非常好看，感谢！
我想请问下怎么在generate阶段控制行间距？
我现在只会修改style.css里面的line-height参数控制。

**Comment by colmugx** [comment]
文章行间距吗？请到`nlvi/source/style/_common/variable.styl`自定义。

另外关于其他基础元素也欢迎自定义。

改之前建议备份，没有备份没关系，到[这里](https://github.com/ColMugX/hexo-theme-Nlvi)可以重新下载

**Comment by hooshooo** [comment]
我修改了一下`variable.styl`，好像不太管用。
后来我改的`normalize.styl`是可以的。

**Comment by colmugx** [comment]
@proverbs 没有问题哦，请问您是要调整哪方面的行间距？

文章修改行间距是完全没问题的

**Comment by hooshooo** [comment]
我刚刚又测试了一下，修改`variable.styl`中的
```
// ======== Space ========
line-height = 1.5
yard = 8px
```
这个部分里的`line-height`对于md中没有任何标签的段落是有效果的，但是对于标签（如列表）的没有效果的。
当然，我写md主要用的是无序列表，所以别的标签我没有做测试。
抱歉我的大部分md都是使用的无序列表，所以没有发现修改这个参数的效果。

**Comment by colmugx** [comment]
如果您用了html标签那么，您就定制您的标签就行了

`line-height`确实目前对文章整个篇幅的段落有作用，目前还没对其他地方产生作用（应该

**Comment by hooshooo** [comment]
恩，`normalize.styl`中的`line-height`应该是控制全局的（我对前端完全不懂...），我改完以后导航栏的间距都变大了，不过效果还不错，眼睛看着舒服很多～
最后感谢主题，我见过的最最最好看的主题

**Comment by colmugx** [comment]
另外为了体验，建议您博客的`_config.yml`中
```
language: en
```
如上填入语言，语言类型查看[这里](https://github.com/ColMugX/hexo-theme-Nlvi/wiki/%E8%AE%BE%E7%BD%AE%E8%AF%AD%E8%A8%80)

其中繁体中文，日语翻译并不完全准确，如果可以欢迎完善 :P

不过这应该也是一个小问题（默认情况），后续我会修改。

**Comment by colmugx** [comment]
谢谢您的喜欢，我们准备了两套风格，也欢迎您尝试`balance`风格。

只需要在主题`_config.yml`切换即可
