### ISSUE TITLE
希望能集成Mathjax功能

### ISSUE THREAD

**Issue by testsiling** [ColMugX/hexo-theme-Nlvi#33]
有许多需要写数学公式的场景
在md头加
<script type="text/javascript"
   src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
好像并没有用。

**Comment by colmugx** [comment]
我记得是有配置过的，针对了一位朋友添加的功能

请在`config.yml`把`mathjax`配置为`true`

如还有问题请告知

更新回复：https://github.com/ColMugX/hexo-theme-Nlvi/blob/master/_config.yml#L110

因为我也没用过，还希望您能协助我把它弄好

**Comment by ruinshe** [comment]
只需要改config不需要加script，如果觉得想自定义，要改的是
`layout/_script/script.swig`

**Comment by testsiling** [comment]
啊抱歉抱歉，我发现还在用第一版，第一版没有mathjax。我现在试试新版，谢谢。

**Comment by testsiling** [comment]
在config.yml中开启了Mathjax，提示cdn已经失效，公式解析不了。
然后去layout/_script/script.swig中
将
<script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
改成
<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"></script>
（官网教的）
依然无法解析公式。
求解

另外希望可以不用每页都加载mathjax，只有在开启了mathjax的页才加载script

**Comment by ruinshe** [comment]
试试`config=TeX-AMS-MML_HTMLorMML`？

**Comment by colmugx** [comment]
换了地址，看了一下确实能载入了。如果有问题欢迎继续追问

**Comment by testsiling** [comment]
改了依然无法正确显示，是只有我有这个问题吗？我现在的_script.swig如下
`
{{ js('script/lib/jquery/jquery-3.2.1.min') }}

{% if theme.lightbox %}
    {{ js('script/lib/lightbox/js/lightbox.min') }}
{% endif %}

{% if theme.mathjax %}
    <script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {inlineMath: [["$","$"]]}});</script>

    <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

{% endif %}

{% if theme.plugins %}
    {% for plugin in theme.plugins %}
        {{js(plugin)}}
    {% endfor %}
{% endif %}

{{ js('script/src/nlvi') }}
{{ js('script/src/utils') }}
{{ js('script/scheme/balance') }}
{{ js('script/src/plugins') }}
{{ js('script/bootstarp') }}
`

**Comment by colmugx** [comment]
我不知道是您的网络问题还是怎么回事。我刚刚用我自己的菜鸡能力随便写了一个公式是能显示的如图：
![image](https://user-images.githubusercontent.com/21327913/37236270-ee767aea-2440-11e8-9651-89c54dbd2d11.png)

不过您提到的按文章选择加载，我觉得值得实现，静候佳音？

**Comment by ruinshe** [comment]
没时间改了。。。按文章加载，给文章加个property就行了。。。类似文章的type这样的，然后在post的模型里面加这句话。。。

另外，我也觉得是网络的问题。。。

**Comment by testsiling** [comment]
按你的改了还是不行，但也没有报错，你能正确显示的话应该是我问题。

**Comment by shadowquark** [comment]
不知道你解決了沒有。。。不過感覺你的 hexo-math 可能沒有成功安裝。。。

**Comment by testsiling** [comment]
没，我最后换了一个主题。。。不过应该是我配置问题。。。

**Comment by shadowquark** [comment]
用别的主题应该也会涉及安装 hexo-math 的问题。。。只要这个能正常安好。应该都是没问题的。。。

**Comment by testsiling** [comment]
@ShadowQuark 用别的主题没有问题。

**Comment by colmugx** [comment]
@testsiling 不好意思打扰了，原谅我拖了好几个月，希望您能理解。我这次重新调整了`mathjax`，希望您能再尝试一次，假如您还有兴趣的话。以下两点关于您需求的解答：

- 您可以关闭`config.yml`的全局`mathjax`，在您想要使用该功能的文章头部加上`mathjax:true`也可以开启功能：
```markdown
---
title:
date: 
tags:
mathjax: true
---
```

- 我专门去了解了一下`mathjax`然后尝试一下并更新了版本，找个了很复杂的公式发现能显示。我不知道您在写公式的时候是否是`$$...$$`的形式，比如
```
$$
\alpha
$$
```
我尝试了这样是没有问题的，还有`\begin{aligned}`, `\end{aligned}`这种

**Comment by ruinshe** [comment]
FYI, `MathJax.Hub.Config` 参数里面的`inlineMath`可以改标记，如果你自己不习惯`$$`可以试试其它的
