### ISSUE TITLE
关于 2.0 版本下，版权信息似乎无法生效

### ISSUE THREAD

**Issue by Kerwong** [ColMugX/hexo-theme-Nlvi#34]
![image](https://user-images.githubusercontent.com/7848790/37535784-b884b210-2983-11e8-88e1-5b15352f7d1b.png)

这是我配置的版权信息，但没生效。
请问下作者大大，配置的对不对啊？

**Comment by colmugx** [comment]
我这边修改没问题，如果您这边还存在问题的话，请给我时间检查一下？

**Comment by colmugx** [comment]
我猜测，您可能是在运行的时候修改的内容。这个时候不会生效。

**Comment by Kerwong** [comment]
我最后在 layout/_partial/_post/copyright.swig 中加入了这一段。

```
<div class="copy-license">
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
        <img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" />
    </a>本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a>进行许可。
</div>
```

效果如下
![image](https://user-images.githubusercontent.com/7848790/39954292-9e0b5afe-55ef-11e8-9c9f-f40b20796639.png)

用着还不错
