### ISSUE TITLE
粗体显示问题

### ISSUE THREAD

**Issue by 31415926535x** [ColMugX/hexo-theme-Nlvi#35]
在markdownpad编辑的md文件中，使用**略略略**这样的粗体语法时，，预览是没有问题的，但是在hexo上不显示粗体，，，

**Comment by colmugx** [comment]
检查你的语法，我也有用粗体

**Comment by 31415926535x** [comment]
语法应该没有问题的，，，两个**号之间的文本不显示啊，，，，我换了其他主题重新git g git s 可以正常显示粗体，，，(๑•̀ㅂ•́)و✧

**Comment by colmugx** [comment]
![image](https://user-images.githubusercontent.com/21327913/38034019-e852ac6e-32d3-11e8-93f3-e94b795aafa0.png)
没问题的喔

**Comment by 31415926535x** [comment]
emmmmm,,,可能是我在加什么效果改文件时弄错了什么了吧┬─┬ノ( º _ ºノ)，，，，，我回去重弄一遍试试♪~ ᕕ(ᐛ)ᕗ

**Comment by 31415926535x** [comment]
应该是style文件夹里的一个文件里font-weight被修改成了400的缘故吧😂😂🤣

**Comment by colmugx** [comment]
我上个星期看过你的博客，粗体能正常显示的。怕不是你自己本身的字体问题…
