### ISSUE TITLE
请问可以更新一下主题吗

### ISSUE THREAD

**Issue by Aneureka** [ColMugX/hexo-theme-Nlvi#36]
偷偷看了你的新主页，更好看了嘤嘤嘤

**Comment by Aneureka** [comment]
还有旧版的好像搜索框没法用诶

**Comment by colmugx** [comment]
我的天..请您更新好嘛嘤嘤嘤

2.0的主题就是，两套风格六种颜色~

首先，头部有块风格和线风格，`config.yml`这个位置修改
```
# Header Style
# line | block
header-style: line
```

其次，整体风格有水平的和垂直的，我目前用的是垂直的
```
# Scheme
# banderole | balance
scheme: banderole
```

接着，这里切换主题颜色，其中初音绿是真官方指定初音绿
```
# theme-style
# miku | sakura | dark | green | blue | purple
theme-style: miku
```

所以使用 `Nlvi`的话相当于有了 2 * 2 * 6 = 24套主题！血赚！

如果您用的是 1.0 请切换到 2.0，如果使用的是 2.0 请重新下载。

**Comment by Aneureka** [comment]
你说的我都已经试过了诶…今天刚用的主题…应该是最新的吧> <
然后就是没有那个“继续阅读”的功能，还有friendlink设置了好像没用，还有搜索框好像用不了…
都怪我不会前端

**Comment by colmugx** [comment]
“继续阅读”是通过您的文章设置的，这也是 hexo 的规则。在想开始省略的位置加上`<!-- more -->`

另外`friendlink`是一个没完成的功能… 主要是不知道放在哪里...

还有搜索，需要配置，Wiki有噢

**Comment by Aneureka** [comment]
谢谢你☺

**Comment by Aneureka** [comment]
对了，那个友链，可以多一个page，然后每个友链用卡片式的结构来排版~ 类似这样：http://bus1996.me/friends/  如果你觉得好看的话~

**Comment by colmugx** [comment]
风格不太相同喔... 不过可以尝试一下，有了就告诉你昂

**Comment by colmugx** [comment]
@Aneureka 不好意思打扰一下，您之前想要的友情链接已经更新了，默认是放在关于下面假如您有设置的话。这里邀请您尝试一下主题如果您还有兴趣的话。

另外我的意愿是让每个第一次操作都有种惊喜感，所以很想尽力每一处都搭配好。有尝试过很好玩的友链展示方式，不过担心后续维护出现问题还是撤掉了，暂时是比较普通的版本。

**Comment by Aneureka** [comment]
哈哈哈，谢谢~ 可以的
