### ISSUE TITLE
建议增加头像、友链、日历、分类、图片模式功能

### ISSUE THREAD

**Issue by hoochanlon** [ColMugX/hexo-theme-Nlvi#37]
先为作者的主题:+1:，建议增加头像、像next主题一样有图片模式以及左或右的相关侧边栏的显示、友链、日历插件等功能，效果如图

![](http://p4.cdn.img9.top/ipfs/QmV5Ff971XFZKCfPCfSU8HWdWYzUyaq7zTUBqm6Az2Ww1K?4.png)

也可默认为原样式，保持不变，我觉得这样非常不错，可选择性大大提高了不少

**Comment by hoochanlon** [comment]
看了下主题的标签，我觉得能用单独的一页显示比较好，可扩展性会稍强一些，毕竟这样可做词云

**Comment by colmugx** [comment]
1. 有人喜欢大而全的主题，有人不喜欢，博客的作用是阅读。

2. 友情链接是有的，目前是在关于页面，个人介绍下方，如果你有设置的话。

3. 你指的图片模式是幻灯片形式？在配置启用`lightbox`即可。

4. 头像对阅读并起不到什么作用，这是Nlvi早期就去掉的元素之一。

4. 从1.0开始就是这种形式的标签云，因为简洁平滑所以决定沿用。

5. 该主题并不止是 NexT，我看到了 Even 的元素。

6. NexT 发展到今天，是因为已经自成社区。Nlvi 孤军奋战有点吃力，如果有好想法还请不吝啬 PR，在此先重谢。

7. 建议开始使用 Nlvi 然后再提意见，因为每个主题的灵魂都是不同的。

**Comment by hoochanlon** [comment]
图片模式像这样
![](http://p0.cdn.img9.top/ipfs/QmZZZpqEu6no7SYJQ9EXc5rUZLzfnMxGNRsGdG3vGEvQ3g?0.png)
