### ISSUE TITLE
1.x切换到2.x后，功能故障

### ISSUE THREAD

**Issue by super2bai** [ColMugX/hexo-theme-Nlvi#38]
####  一、文章导航丢失
效果页面：https://super2bai.github.io/Docker/start.html
现象：观察其它导航可以正常显示的页面后，发现导航栏应该有一个动画，横线变为竖线，点击后再显示导航内容。问题页面，一直处于横线状态，没有变成动画效果，并报错`imgHead is not defined`

---

20180730更新
点击导航后，页面报错：`Uncaught TypeError: Cannot read property 'apply' of undefined`，在`nlvi.js:31`

#### 二、赞赏功能图片未显示（已解决-20180730）
效果页面：https://super2bai.github.io/Docker/start.html
现象：“赞赏”二字显示，鼠标点击后，赞赏图片未显示。
20180730更新
已解决，给作者一个大拇哥！

#### 三、搜索功能（已解决-20180730）
1.在theme的`_config.yml`中配置`search`的`enable:false`，并且在博客的`_config.yml`中移除`search`节点，生成的页面菜单中仍有搜索菜单。
2.如果在theme的`_config.yml`中移除`search`节点，生成页面会报错，详见下方`search`节点，value为空，推荐添加默认值`false`
```
  var nlviconfig = {
    title: "贰白",
    author: "super2bai",
    baseUrl: "/",
    theme: {
      scheme: "banderole",
      lightbox: true,
      animate: true,
      search: ,
      friends: false,
      lazy: false
    }
  }
```

#### 四、找不到`lightbox.min.map`（已解决-20180730）
操作：1.将`Nlvi`项目`master`分支下载后，重命名为`Nlvi`，放到`theme`文件夹下，生成页面报错
`[Error] Failed to load resource: the server responded with a status of 404 ()  https://super2bai.github.io/script/lib/lightbox/js/lightbox.min.map`

另：十分喜欢此主题，感谢作者。昨天刚切换到2.x版本，新版本配置还在逐步调整中。

**Comment by colmugx** [comment]
给您带来不便了，特别抱歉。

如果发现新问题，还请直接在顶楼直接修改。方便我跟踪。

- [x] 文章导航丢失
- [x] 赞赏功能
- [x] 搜索菜单
- [x] 找不到lightbox.min.map

**Comment by colmugx** [comment]
您的第一个问题已经解决，做了图片的懒加载然后有个遗漏。

第二个纯属忘记适配..从1.x搬过来之后完全没用过，需要时间..

**Comment by colmugx** [comment]
您的第一个问题已经解决，做了图片的懒加载然后有个遗漏。

第二个纯属忘记适配..从1.x搬过来之后完全没用过，需要时间..

**Comment by colmugx** [comment]
问题全部解决，请尝试更新，还有问题欢迎回复。
另外关于赞赏功能新增一个功能：赞赏文字自定义，配置可从`_config.yml`检查，效果如下：
![image](https://user-images.githubusercontent.com/21327913/43352797-b50f7232-925b-11e8-98bd-33bc9106b9b9.png)
不过这个不是我想要的设计，以后会重新设计“赞赏”按钮的样式和位置
