### ISSUE TITLE
自定义页面，除了about其余都无法生成内容

### ISSUE THREAD

**Issue by miranquil** [ColMugX/hexo-theme-Nlvi#39]
重现过程：
`hexo new page test`

> INFO  Created: ~/project/blog/source/test/index.md

打开index.md，加入内容`type: 'test'`以及正文内容，并设置主题_config.yml中menu项，加入`test: /test`，编辑对应language的yml加入对应翻译。执行`hexo clean && hexo generate && hexo server`。进入本地主页显示正常，点击test链接进入后显示是空内容页面，有博客框架但正文内容为空。

**Comment by miranquil** [comment]
有什么发现么？

**Comment by colmugx** [comment]
不明白你想要什么。目前默认是除了 about 页没有显示需求。
可以看这里：[page.swig](https://github.com/colmugx/hexo-theme-Nlvi/blob/master/layout/page.swig)

**Comment by miranquil** [comment]
就是说可能用户会想添加其他的类似about这种自定内容的页面，我diy一下好了。
