### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by liurui39660** [ColMugX/hexo-theme-Nlvi#43]
我看到`_source/about/index.md`里有`comments: false`，但是这行似乎并没有起到任何效果，评论区仍然会显示出来

实际上，即便是在普通的post里，这行代码也没有什么用，并不能阻止评论区的显示

**Comment by liurui39660** [comment]
还有两个小问题，不再新开个issue了，这里顺便一提：
1. 导航栏的article从英语语法上讲应该是articles
1. 建议导航栏的单词改成首字母大写（针对非英语的场合）

**Comment by liurui39660** [comment]
更多的问题，这次是手机版

![image](https://user-images.githubusercontent.com/20491264/44807174-6f76d580-abfb-11e8-9c94-40c3e9d31733.png)

没有搜索按钮，需要先点一下stack按钮才能恢复到正常的打开状态，然后点X关闭，之后可以正常地切换开关了

另外我设置的`mobile-header: dark`似乎并没有效果

**Comment by liurui39660** [comment]
另外的一个问题属于我个人的猜测

![wlfoomyq3rccomdgaxie](https://user-images.githubusercontent.com/20491264/44807727-df399000-abfc-11e8-9b90-69adca770953.gif)

这里当我输入文字的时候，原本希望达到的效果是不是“搜索一下”在原地淡出，或者向上移动的同时淡出？
而不是像现在这样：文字突然移动到上方，然后淡出

**Comment by liurui39660** [comment]
about页的渲染和post页的渲染不一样？

about页对链接的渲染
![image](https://user-images.githubusercontent.com/20491264/44824428-0d889100-ac38-11e8-9f6b-ab6263137ef2.png)
post页对链接的渲染
![image](https://user-images.githubusercontent.com/20491264/44831950-4b4ae100-ac5b-11e8-9771-bbdee2b212da.png)
这只是其中一个地方，实际上诸如列表等也都很不一样

似乎about页仅仅是把md渲染成了html，却没有添加任何css样式

因为about页个人信息有点多，我就不放截图了

**Comment by colmugx** [comment]
有一部分问题是代码迁移的时候迁出事了，很多细节的东西丢失，在慢慢找回补齐。许多开关都可能失效了。

about 页默认只有文字样式，而且这个页面的设定有点争议，需要调整。

链接变紫色是因为该链接被点击过，属于浏览器一个功能。暂时保留浏览器这项设定吧。

搜索页那个问题是丢失了一个动画，动画库在之前调整过一次。

给您带来不便请您谅解

**Comment by colmugx** [comment]
都基本修复了一下，还有问题欢迎继续反馈。

关于评论区：配置的开关比文章的开关权限高，一般在全局关闭的情况下可以指定某些文章开启。
部分样式问题：抽时间重构
