### ISSUE TITLE
文章导航在展开后突然消失

### ISSUE THREAD

**Issue by liurui39660** [ColMugX/hexo-theme-Nlvi#45]
![dsfijycbtebopzngur2x](https://user-images.githubusercontent.com/20491264/45017315-e4159e00-b059-11e8-86c1-8f563ce0fba8.gif)

查看源码，问题似乎出现在这里

![ogbzdscvr9x5i0rofsxi](https://user-images.githubusercontent.com/20491264/45018065-ca755600-b05b-11e8-9361-3535777281ee.gif)

特别注意到第一次点开文章导航并没有问题，但是后面会出现这个问题

附：
Nlvi版本commit f31e982，Chrome 68，Windows 10，`npm ls --depth=0`输出为

```
hexo-site@0.0.0 E:\lenovo\OneDrive\Blog
+-- hexo@3.7.1
+-- hexo-browsersync@0.3.0
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-search@2.2.5
+-- hexo-generator-seo-friendly-sitemap@0.0.21
+-- hexo-generator-tag@0.2.0
+-- hexo-inject@1.0.0
+-- hexo-math@3.0.4
+-- hexo-pdf@1.1.1
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.3.3
`-- hexo-uuid@1.0.1
```

**Comment by colmugx** [comment]
有没有相关地址，排查了一遍没有这种情况
