### ISSUE TITLE
markdown表格样式无法正确显示

### ISSUE THREAD

**Issue by counter2015** [ColMugX/hexo-theme-Nlvi#48]
markdown 表格显示不正常，如下图
![](http://ww1.sinaimg.cn/large/005OIjE6ly1fxmgtjzy5nj30bj052t8x.jpg)
但是如果在同一目录下导出同名pdf文件，则会正常显示
![](http://ww1.sinaimg.cn/large/005OIjE6ly1fxmgudriyrj30rr09v3yy.jpg)
表格代码如下
```
| 文件夹  | 描述                             |
| ------- | :------------------------------- |
| /bin/   | 用于启动和停止服务的驱动程序脚本 |
| /etc/   | 配置文件                         |
| /lib/   | 系统服务                         |
| /logs/  | 日志文件                         |
| /share/ | jar包和许可证                    |
| /src/   | 依赖于构建平台的源文件           |
```
| 文件夹  | 描述                             |
| ------- | :------------------------------- |
| /bin/   | 用于启动和停止服务的驱动程序脚本 |
| /etc/   | 配置文件                         |
| /lib/   | 系统服务                         |
| /logs/  | 日志文件                         |
| /share/ | jar包和许可证                    |
| /src/   | 依赖于构建平台的源文件           |

markdown编辑器 Typora
博客框架 hexo
操作系统 win10
浏览器 chrome

**Comment by colmugx** [comment]
没用过表格，纯属疏忽，可以改进，谢谢提出问题

**Comment by colmugx** [comment]
更新了与主题风格相近的表格展示，看下是否喜欢

接下来可能会有一次大的设计升级，可以继续关注假设你喜欢的话
