### ISSUE TITLE
归档404

### ISSUE THREAD

**Issue by testsiling** [ColMugX/hexo-theme-Nlvi#5]
我的配置：
`#navigation
menu:
  article: /
  archives: /archives
  tags: /tags
  about: /about
  RSS: /atom.xml`

点击首页归档后404

**Comment by Miiog** [comment]
已解决，忘了下插件
$ npm install hexo-generator-archive --save

**Comment by Miiog** [comment]
已解决，忘了下插件
$ npm install hexo-generator-archive --save

**Comment by testsiling** [comment]
已解决，忘了下插件
$ npm install hexo-generator-archive --save
