### ISSUE TITLE
navigation的menu配置问题

### ISSUE THREAD

**Issue by ddzy** [ColMugX/hexo-theme-Nlvi#50]
### 问题一: 使用中文作url的话, 会这样
![issue_bug_1](https://user-images.githubusercontent.com/33921398/51426488-91aed580-1c26-11e9-9221-98565db1188a.jpg)
![issue_bug_2](https://user-images.githubusercontent.com/33921398/51426487-8e1b4e80-1c26-11e9-9ba2-36e9efb9040e.jpg)

### 问题二: 搜索功能无法使用
![issue_bug_3](https://user-images.githubusercontent.com/33921398/51426520-fa964d80-1c26-11e9-9ddd-66cba22e19ce.jpg)

## Expected Feature
希望阔以解决一下🤔

**Comment by colmugx** [comment]
关于语言，并不需要这么改，参考[语言wiki](https://github.com/colmugx/hexo-theme-Nlvi/wiki/%E8%AE%BE%E7%BD%AE%E8%AF%AD%E8%A8%80)

还有这是[搜索wiki](https://github.com/colmugx/hexo-theme-Nlvi/wiki/%E8%AE%BE%E7%BD%AE%E7%AB%99%E5%86%85%E6%90%9C%E7%B4%A2)

目前主题的设计正在重构，可以期待一下

**Comment by ddzy** [comment]
> 关于语言，并不需要这么改，参考[语言wiki](https://github.com/colmugx/hexo-theme-Nlvi/wiki/%E8%AE%BE%E7%BD%AE%E8%AF%AD%E8%A8%80)
> 
> 还有这是[搜索wiki](https://github.com/colmugx/hexo-theme-Nlvi/wiki/%E8%AE%BE%E7%BD%AE%E7%AB%99%E5%86%85%E6%90%9C%E7%B4%A2)
> 
> 目前主题的设计正在重构，可以期待一下

稳的很🤞
