### ISSUE TITLE
[Feature Request] 固定header

### ISSUE THREAD

**Issue by ddzy** [ColMugX/hexo-theme-Nlvi#56]
## Expected Feautre
PC端, 文章内容滚动的时候, 可以考虑固定一下`header区域`.

**Comment by colmugx** [comment]
https://colmugx.github.io/blog/

如果是这种的话，可以期待一下

**Comment by ddzy** [comment]
> https://colmugx.github.io/blog/
> 
> 如果是这种的话，可以期待一下

不错喔🤞

**Comment by ddzy** [comment]
> https://colmugx.github.io/blog/
> 
> 如果是这种的话，可以期待一下

坐等

**Comment by colmugx** [comment]
@ddzy 是否有兴趣体验一下？

[Nlvi-3 dev ](https://github.com/colmugx/hexo-theme-Nlvi/tree/dev-3)

**Comment by ddzy** [comment]
> @ddzy 是否有兴趣体验一下？
> 
> [Nlvi-3 dev ](https://github.com/colmugx/hexo-theme-Nlvi/tree/dev-3)

已用上, 但是有一些显示问题, 我会陆续提出来.
![gayhub_issue_1](https://user-images.githubusercontent.com/33921398/56006960-7cb77f00-5d09-11e9-936b-5b643eac2838.png)

**Comment by colmugx** [comment]
已经合并到 `master` 了，`archive` 这部分是有想过就这么设计的，忽视了篇幅短的情况…我改进一下

有新问题开新 issue 吧，这个我关了
