### ISSUE TITLE
[Bug] 导航栏空链接

### ISSUE THREAD

**Issue by ddzy** [ColMugX/hexo-theme-Nlvi#58]
## Version
branch@dev-3

## Current Feature
本地服务器测试, `TAGS`链接为空:
![gayhub_issue_2](https://user-images.githubusercontent.com/33921398/56011620-12a7d580-5d1b-11e9-8bb9-3d8c34790af6.png)
![gayhub_issue_3](https://user-images.githubusercontent.com/33921398/56011621-12a7d580-5d1b-11e9-900f-44daa75eb862.png)

## Expected Feature

**Comment by colmugx** [comment]
有没有试过 `hexo clean`？
