### ISSUE TITLE
“关于”页面的链接文字样式消失

### ISSUE THREAD

**Issue by Roger-WIN** [ColMugX/hexo-theme-Nlvi#60]
最近更新了 Nlvi 主题，其配置文件由 2.4 更新到了 3.0。但是随之而来，我发现了一些 bug，下面是其中一个。

![image](https://user-images.githubusercontent.com/25821208/58262225-77d7f780-7dac-11e9-9918-a323e9277243.png)
![image](https://user-images.githubusercontent.com/25821208/58262258-8aeac780-7dac-11e9-9897-be68381495f4.png)
上面是 about 页面文字中，旧版与新版的对比图。可以看到旧版的文字着色以及下划线在新版中都不见了。

**Comment by colmugx** [comment]
emm，我更倾向是保持统一性。不过非常感谢，关于高亮链接接下来会做出改动

**Comment by Roger-WIN** [comment]
ummm，我想的是，总得能看出来这是个链接吧，没有高亮就完全变成普通文字了。
