### ISSUE TITLE
顶部导航栏变成英文

### ISSUE THREAD

**Issue by Roger-WIN** [ColMugX/hexo-theme-Nlvi#61]
![image](https://user-images.githubusercontent.com/25821208/58262919-b7ebaa00-7dad-11e9-9acc-fe92e68e1d68.png)
![image](https://user-images.githubusercontent.com/25821208/58262935-c2a63f00-7dad-11e9-8dc1-009e0b8ddac4.png)
博客语言为中文的情况下，导航栏为英文。

**Comment by colmugx** [comment]
有点不好意思，为了更加统一美观，非英文模式下也取消了原文显示。

不过这点确实是我有所不妥，未来会做纯中文（或其他语言）菜单显示~

**Comment by colmugx** [comment]
[_config.template.yml#L23](https://github.com/colmugx/hexo-theme-Nlvi/blob/master/_config.template.yml#L23)

现在可以选择是本地化语言菜单还是为了美观使用大写英文菜单

```yaml
# Navigator Language
local-nav: false
```
