### ISSUE TITLE
打赏二维码图片不能展开

### ISSUE THREAD

**Issue by Roger-WIN** [ColMugX/hexo-theme-Nlvi#62]
![image](https://user-images.githubusercontent.com/25821208/58263129-0c8f2500-7dae-11e9-8a78-e817a4efd17b.png)
在点击上面的 span 之后，二维码图片不会展开显示出来。

![image](https://user-images.githubusercontent.com/25821208/58263473-9d660080-7dae-11e9-9f69-9df8b85ddef8.png)
看起来可能是此处 `display:none` 的缘故。
![image](https://user-images.githubusercontent.com/25821208/58263572-d7370700-7dae-11e9-9325-1bc94d6d85df.png)
之前能正常显示时是 `display:flex`。

**Comment by colmugx** [comment]
非常抱歉，这个完全是我的失误。更新主题之后这部分几乎被遗忘了…

如果有以前使用过的功能现在无法正常使用的欢迎联系
