### ISSUE TITLE
点击标签后不出现相应的文章

### ISSUE THREAD

**Issue by Roger-WIN** [ColMugX/hexo-theme-Nlvi#65]
![image](https://user-images.githubusercontent.com/25821208/58265662-aeb10c00-7db2-11e9-8ce8-4b584ab829af.png)
可以看到，在点击 div 后，没有被标为 `active`，所以不会出现文章。
这一现象时有发生，而且只出现于部分标签，多数标签都是正常的。
此外，在我的测试中，这个现象只会在使用油猴脚本[空格之王 自动为中英文之间添加一个空格](https://greasyfork.org/zh-CN/scripts/37950-%E7%A9%BA%E6%A0%BC%E4%B9%8B%E7%8E%8B-%E8%87%AA%E5%8A%A8%E4%B8%BA%E4%B8%AD%E8%8B%B1%E6%96%87%E4%B9%8B%E9%97%B4%E6%B7%BB%E5%8A%A0%E4%B8%80%E4%B8%AA%E7%A9%BA%E6%A0%BC)时出现，禁用该脚本之后马上就正常了。😂

**Comment by colmugx** [comment]
这个需要一个详细一点的说明，如果是因为插件/脚本导致的问题，我只能看情况解决了

**Comment by colmugx** [comment]
看来是解决了，可以试试看还有没有问题
