### ISSUE TITLE
希望能让表格居中

### ISSUE THREAD

**Issue by Roger-WIN** [ColMugX/hexo-theme-Nlvi#69]
![image](https://user-images.githubusercontent.com/25821208/59603336-c07c9980-913b-11e9-81dc-e7df42c9a39c.png)
现在的表格整体是居左的，感觉显得不是很美观，居中要好看一些。

**Comment by colmugx** [comment]
已更新为居中，暂时先看看有没有什么问题，或者有更好的实践~

**Comment by Roger-WIN** [comment]
![image](https://user-images.githubusercontent.com/25821208/59894946-26577280-9415-11e9-9cf4-3560b4deb3d6.png)
这……上下两个表格之间的间距怎么没有了，看起来像是合起来了一样。

**Comment by colmugx** [comment]
改动错位置的代码，测试不周导致的问题，非常抱歉

**Comment by Roger-WIN** [comment]
没事没事。😃
