### ISSUE TITLE
代码可以高亮吗

### ISSUE THREAD

**Issue by qmaqma573** [ColMugX/hexo-theme-Nlvi#7]
用了你的主题，想问问代码能高亮吗--

**Comment by colmugx** [comment]
可以啊，截图不是显示了高亮的style了嘛。

颜色比较清淡，以后可能针对颜色这块会丰富一下。

**Comment by colmugx** [comment]
建议你用标准的markdown代码块来做。我看了一眼您的博客。您可以这么写
\```C
// Code
\```

另外看你的id像个大hacker

**Comment by colmugx** [comment]
记得star喔，我关闭了
