### ISSUE TITLE
[Suggestion] 集成gittalk

### ISSUE THREAD

**Issue by ddzy** [ColMugX/hexo-theme-Nlvi#70]
## Current Feature

`gitment`各种抽风, 无法正常登录、评论

[作者](https://github.com/imsun/gitment)貌似已经弃坑了?

## Expected Feature

希望可以引进`gittalk`评论插件:

https://github.com/gitalk/gitalk

**Comment by colmugx** [comment]
没用过这些东西…
不过谢谢你的建议，我把`gitment`换成`gitalk`了。

没用的东西不值得保留（大雾

**Comment by ddzy** [comment]
可以正常使用!
