### ISSUE TITLE
[Suggestion] 增加批量文章置顶首页功能

### ISSUE THREAD

**Issue by ddzy** [ColMugX/hexo-theme-Nlvi#71]
## Expected Feature

想将一些文章常置于首页, 现在默认的是按时间排的, 希望可以添加这个功能.

**Comment by colmugx** [comment]
主题支持了，不过你要自己整一个`hexo-generator-index-pin-top`

![image](https://user-images.githubusercontent.com/21327913/61993527-8c33bb80-b09f-11e9-8218-221c17fe85e2.png)

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
