### ISSUE TITLE
lightbox和hexo原生的 image tag 有冲突？

### ISSUE THREAD

**Issue by wangzitian0** [ColMugX/hexo-theme-Nlvi#8]
您好，您做的这个 hexo 主题很漂亮，我打算用这个来作为我自己博客的模板。
但是插入图片的部分似乎有一些问题，hexo 文档里面的 tag 提供了类似于这样的语法：
{% img [class names] /path/to/image [width] [height] [title text [alt text]] %}
{% img ggggtest /images/gopher.png 180 180 'title text' 'alt text' %}

图片的大小始终都是静态样式里的500x500px…
我把lightbox: false之后显示正常，我目前还不是很清楚内在的原理。
或者能说说你自己是怎么插指定大小图片么？

**Comment by colmugx** [comment]
我在做lightbox适配的时候顺便控制了图片的大小。而且关于图片的细节适配我还没去细究。
说实话主题只是表面看起来很不错实际上还有一些细节问题。这些问题会慢慢发现并修复的。

给您添麻烦了。（鞠躬
问题我会解决的
