### ISSUE TITLE
主题文件夹中无_config.yml

### ISSUE THREAD

**Issue by J-Corleone** [ColMugX/hexo-theme-Nlvi#80]

**Comment by J-Corleone** [comment]
怎么办呢

**Comment by J-Corleone** [comment]
我好像明白了，是不得从模板那复制一份...

我换成这个主题后网页就变成代码了，是为啥呢

**Comment by colmugx** [comment]
配置是 `_config.template.yml` 复制一份或者直接删掉`template`使用

另外变成代码什么的，最好有个截图还是能更精确描述问题的材料以便排查

你也可以先试试 `hexo clean` 之后再使用
