### ISSUE TITLE
請問為什麼hexo s開起來之後，網站內容怪怪的

### ISSUE THREAD

**Issue by thekuen** [ColMugX/hexo-theme-Nlvi#81]
hexo s開起來之後，往內容如下圖
<img width="632" alt="image" src="https://github.com/colmugx/hexo-theme-Nlvi/assets/138368310/c3a4d85d-3bc1-4752-8048-f6a1dfff56d3">

{% extends "_layout.swig" %} {% block title %} {{config.title}} {% if config.subtitle %} | {{ config.subtitle }} {% endif %} {% endblock %} {% block main %} {% include "_partial/main.swig" %} {% include "_partial/pagenum.swig" %} {% endblock %}

**Comment by colmugx** [comment]
您好，我猜你之前用了別的 `theme` 造成了衝突。你可以 `hexo clean` 選項，把快取資料清掉
很難得您竟然還對這個專案有興致

**Comment by thekuen** [comment]
**感謝您回覆**
```hexo clean```還是沒辦法解決，出現一樣的畫面
最後改用hexo-theme-next的主題，因為趕著要部屬網站
