### ISSUE TITLE
前排征集配色

### ISSUE THREAD

**Issue by colmugx** [ColMugX/hexo-theme-Nlvi#9]
本来一开始就有多种配色的计划。但是后来自己相对的配了一下发现并没有白底黑字看起来有灵性。

不过报纸一样的风格应该会有人不喜欢吧

所以我打算征集配色方案！甚至开放自定义颜色的功能！

这个对kindle来说特别喜欢的网站，现在要添加颜色了！

**Comment by usayao** [comment]
迫切需要颜色~

**Comment by colmugx** [comment]
@usayao 咦？

可能下个版本就有了！

**Comment by colmugx** [comment]
@usayao 您迫切需要的颜色，现已支持！
